services:
  python3:
    # restart: always
    build: .
    container_name: 'python3'
    ports:
      - "4486:8888"
    tty: true
    working_dir: "/haru"
    volumes:
      - "./haru:/haru"
    command: jupyter lab --ip 0.0.0.0 --port 8888 --allow-root --no-browser --NotebookApp.token=''
